# **Linear Algebra Tasks**

## Task 1: Matrix and Vector Computations in python
In this task you will use python to study the following topics:

- How to create matrices and vectors in python.

- How to manipulate matrices in python and create matrices of special types.

- How to add matrices and multiply a vector by a matrix by python.

- Solving System of Linear Equations Using Gaussian Elimination.

- Matrix Multiplication using Different views.

# First: you should run this cell

In [ ]:
# Make all numpy available via shorter 'np' prefix
import numpy as np

import sympy as sym

# Question 1(Warm Up!) :Declaring scalars, vectors, and matrices

a) Use [numpy.array](https://numpy.org/doc/stable/reference/generated/numpy.array.html) to declare the following:

#### 1. A scalar $s = 5$

#### 2. A vector $v = \begin{bmatrix} 5  \\ -2 \\ 4  \\ \end{bmatrix}$
#### 3. A matrix $A = \begin{bmatrix} 1 & 2 & 3  \\ 4 & 5 & 6 \\ 7 & 8 & 9  \\ \end{bmatrix}$
#### 4. A matrix $B = \begin{bmatrix} 1 & 2 & 3  \\ 4 & 5 & 6 \\ \end{bmatrix}$
#### 5. A matrix $C = \begin{bmatrix} 1 & 2   \\ 3 & 4  \\ 5 & 6   \\ \end{bmatrix}$

In [ ]:
#type your code here:
import numpy as np

s = np.array(5)

v = np.array([5, -2, 4]) 

A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

B = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

C = np.array([
    [1, 2],
    [3, 4],
    [5, 6]
])

b) Print the data type of $s, v,$ and $A$ using `type` command in python.

In [ ]:
#type your code here:
print(type(s))
print (type(v))
print (type(A))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


c) Using [numpy.shape](https://numpy.org/devdocs/reference/generated/numpy.shape.html) or `A.shape` print the shape of $s, v, A, B,$ and $C$.

In [ ]:
#type your code here:
print(s.shape)
print(v.shape)
print(A.shape)
print(B.shape)
print(C.shape)



()
()
(3,)
(3, 3)
(2, 3)
(3, 2)


d) To access a given entry in the `numpy array` put the `row number - 1` and `column number - 1` in square brackets following the array name. Ex `a32 = A[2, 1]`.
- Print the value of the third row and the second column of the matrix $A$.
- Change it to $10$.
- Print the matrix A to check the entry is changed.

In [ ]:
#type your code here:
print (A[2,1])
A[2,1] = 10
print (A)

8
[[ 1  2  3]
 [ 4  5  6]
 [ 7 10  9]]


e)To access a whole row or column of a matrix, use the colon operator. For example, `A[:, [1]]` is the second column of A, while `B[[1], :]` is the second row of B.

In [ ]:
#type your code here:
print("A[:,[1]] = ", A[:,[1]])
print("B[[1],:] = ", B[[1],:])

A[:,[1]] =  [[ 2]
 [ 5]
 [10]]
B[[1],:] =  [[4 5 6]]


f) Type each of the following commands that generate special matrices:
- `np.eye(4), np.zeros(3), np.zeros((3, 1)), np.zeros((3, 5)), np.ones((2, 3)), and np.diag([4, 5, 6, 7])`

In [ ]:
#type your code here:
np.eye(4)
np.zeros(3)
np.zeros((3,1))
np.zeros((3,5))
np.zeros((2,3))
np.diag([4,5,6,7])

array([[4, 0, 0, 0],
       [0, 5, 0, 0],
       [0, 0, 6, 0],
       [0, 0, 0, 7]])

# Question 2. Vectors Addition, Scaling, and dot product

a) Declare vectors $v1 = \begin{bmatrix} 1  \\ 2 \\ 7  \\ 4 \\ \end{bmatrix}$ and $v2 = \begin{bmatrix} 4  \\ 3 \\ 6  \\ 8 \\ \end{bmatrix}$

- Addition: $v1 + v2$
- Subtraction: $v1 - v2$
- Scaling by a number: $3 * v1$

In [ ]:
#type your code here
v1 = np.array( [1, 2, 7, 4])

v2 = np.array([4, 3, 6, 8])

print("v1 + v2 =", v1 + v2)
print("v1 - v2 =", v1 - v2)
print("3 * v1 =", 3 * v1)


v1 + v2 = [ 5  5 13 12]
v1 - v2 = [-3 -1  1 -4]
3 * v1 = [ 3  6 21 12]


b) Find the dot product between the two vectors $v1$ and $v2$ using the following:

- [numpy.dot](https://numpy.org/doc/stable/reference/generated/numpy.dot.html)
- [numpy.matmul](https://numpy.org/doc/stable/reference/generated/numpy.matmul.html#numpy.matmul)
- `v1.T @ v2`

In [ ]:
#type your code here:
print("Using the dot product: ", np.dot(v1, v2))
print("Using the multiple product: ", np.matmul(v1,v2))
print("Using V1.T @ V2: ", v1.T @ v2)



Using the dot product:  84
Using the multiple product:  84
Using V1.T @ V2:  84


c) Find the length of the vectors $v1$ and $v2$.
- Using [numpy.linalg.norm](https://numpy.org/doc/stable/reference/generated/numpy.linalg.norm.html)
- Using the dot product and [numpy.sqrt](https://numpy.org/doc/stable/reference/generated/numpy.sqrt.html)


In [ ]:
#type your code here:
print("length of v1 Using numpy.linalg.norm = ", np.linalg.norm(v1))
print("length of v2 Using numpy.linalg.norm = ", np.linalg.norm(v2))
print("length of v1 Using the dot product and numpy.sqrt = ", np.sqrt(np.dot(v1,v1)))
print("length of v2 Using the dot product and numpy.sqrt = ", np.sqrt(np.dot(v2,v2)))

length of v1 Using numpy.linalg.norm =  8.366600265340756
length of v2 Using numpy.linalg.norm =  11.180339887498949
length of v1 Using the dot product and numpy.sqrt =  8.366600265340756
length of v2 Using the dot product and numpy.sqrt =  11.180339887498949


d) Show that the vectors $u = \begin{bmatrix} 3  \\ 2 \\ -1  \\ 4 \\ \end{bmatrix}$ and $v = \begin{bmatrix} 1  \\ -1 \\ 1  \\ 0 \\ \end{bmatrix}$ are orthogonal.


In [ ]:
#type your code here:
u = np.array([3,2,-1,4])
v = np.array([1,-1,1,0])

dot_prod = np.dot(u,v)

print("Dot product = ", dot_prod)

if dot_prod == 0:
    print("Since the dot product is 0, the vectors are orthogonal.")
else:
    print("The vectors are not orthogonal.")

Dot product =  0
Since the dot product is 0, the vectors are orthogonal.


# Question 3. Matrix Addition and Matrix-Vector Multiplication

Declare vectors $u$ and $v$ and matrices $A$ and $B$ as following:
- $u = \begin{bmatrix} 2  \\ 7 \\ 2 \\ \end{bmatrix}$, $v = \begin{bmatrix} 8  \\ 2 \\ 4 \\ \end{bmatrix}$
- $A = \begin{bmatrix} 7 & 3 & 5  \\ 4 & 6 & 2 \\ \end{bmatrix}$, $B = \begin{bmatrix} 0 & 6 & 4  \\ 2 & 3 & 0 \\ \end{bmatrix}$

a) Calculate the following using python.

- $A+B$
- $B+A$
- $3A$
- $6B$
- $2(3B)$
- $6A+15B$
- $3(2A+5B)$
- $(3A^T)^T$

In [ ]:
#type your code here:
u = np.array ([2,7,2])
v = np.array ([8,2,4])

A = np.array ([[7,3,5],[4,6,2]])

B = np.array ([[0,6,4], [2,3,0]])

print("A + B = \n", A + B)
print("B + A = \n", B + A)
print("3A = \n", 3*A)
print("6B =\n", 6*B)
print("2(3B) =\n", 2*(3*B))
print("6A + 15B =\n",6*A+15*B)
print("3(2A + 5B)=\n",3*(2*A+5*B))
print("(3At)t =\n", (3 * A.T).T)


A + B = 
 [[7 9 9]
 [6 9 2]]
B + A = 
 [[7 9 9]
 [6 9 2]]
3A = 
 [[21  9 15]
 [12 18  6]]
6B =
 [[ 0 36 24]
 [12 18  0]]
2(3B) =
 [[ 0 36 24]
 [12 18  0]]
6A + 15B =
 [[ 42 108  90]
 [ 54  81  12]]
3(2A + 5B)=
 [[ 42 108  90]
 [ 54  81  12]]
(3At)t =
 [[21  9 15]
 [12 18  6]]


b) To obtain the matrix-vector product $Au$ using python, type `A @ u`. Calculate the following:

- $Au+Av$
- $A(u+v)$
- $(A+B)u$
- $Au+Bu$
- $A(3u)$
- $3A(u)$

In [ ]:
#type your code here:
print("Au + Av = \n", A@u + A@v)
print("A(u + v) = \n", A @ (u + v))
print("(A + B)u = \n", (A + B) @ u)
print("Au + Bu = \n", A @ u + B @ u)
print("A(3u) = \n", A @ (3 * u))
print("3A(u) = \n", 3*(A @ u))

Au + Av = 
 [127 106]
A(u + v) = 
 [127 106]
(A + B)u = 
 [95 79]
Au + Bu = 
 [95 79]
A(3u) = 
 [135 162]
3A(u) = 
 [135 162]


# Question 4. Gaussian Elimination and Reduced Row-Echelon Form

You will see a step-by-step example of the row operations that transform a matrix $A$ into its reduced row echelon form $R = rref(A)$. In this demonstration, each pivot is chosen to be the largest in its column (for numerical stability), so extra row interchanges are used. Since $rref(A)$ is uniquely determined by $A$, this does not affect the final answer.

The built in [rref](https://docs.sympy.org/latest/tutorial/matrices.html#rref) method `sympy.rref()` method just search for the method and its output to deal with the code.

#### (a) Generate and display a $3 \times 4$ matrix $A$ with random integer entries

In [ ]:
#type your code here:
A = np.fix((10*(np.random.rand(3,4))))
print("\n A = \n", A)


 A = 
 [[0. 6. 5. 1.]
 [9. 3. 7. 6.]
 [5. 8. 9. 2.]]


- To transform $A$ into $R = rref(A)$, start with $R = A$.
- Normalize the first row of R to get R(1st row, 1st column) = 1

    - `R = A`
    - `R[0,:] = R[0, :] / R[0, 0]`

(note the use of the colon to operate on whole rows of the matrix).

<div class="alert alert-block alert-warning">If your random matrix happens to have A(1, 1) = 0, then interchange rows to get a nonzero entry in the (1, 1) position before doing the calculation above.</div>

- Now subtract a multiple of the first row of R from the second row to make R(2, 1) = 0:

    - `R[1, :] = R[1, :] - R[1, 0] * R[0, :]`

- Repeat this procedure to make R(3, 1) = 0:

    - `R[2, :] = R[2, :] - R[2, 0] * R[0, :]`

The first column of your matrix $R$ should now be the same as the first column of $rref(A)$.

In [ ]:
R=A
#type your code here:
R[0,:] = R[0, :] / R[0, 0]
R[1,:] = R[1, :] - R[1, 0] * R[0, :]
R[2,:] = R[2, :] - R[2, 0] * R[0, :]

# print R here
print(R)


[[ nan  inf  inf  inf]
 [ nan -inf -inf -inf]
 [ nan -inf -inf -inf]]


C:\Users\ahmed\AppData\Local\Temp\ipykernel_6012\3936924945.py:3: RuntimeWarning: divide by zero encountered in divide
  R[0,:] = R[0, :] / R[0, 0]
C:\Users\ahmed\AppData\Local\Temp\ipykernel_6012\3936924945.py:3: RuntimeWarning: invalid value encountered in divide
  R[0,:] = R[0, :] / R[0, 0]


#### (b)Operate on $R$ by the same method as in (a) to obtain the second column of $rref(A)$. First normalize row $2$ of $R$, then subtract multiples of row $2$ from rows $1$ and $3$ to put zeros in the (1, 2) and (3, 2) positions. Be sure to refer to the entries in your matrix symbolically as was done in part (a)

In [ ]:
#type your code here:
R[1,:] = R[1, :] / R[1, 1]
R[0,:] = R[0, :] - R[0, 1] * R[1, :]
R[2,:] = R[2, :] - R[2, 1] * R[1, :]



# Print R here
print(R)

[[nan nan nan nan]
 [nan nan nan nan]
 [nan nan nan nan]]


C:\Users\ahmed\AppData\Local\Temp\ipykernel_6012\1115485735.py:2: RuntimeWarning: invalid value encountered in divide
  R[1,:] = R[1, :] / R[1, 1]


#### (c) Operate on $R$ by the same method as in (b) to obtain the third column of $rref(A)$. First normalize row $3$ of $R$, then subtract multiples of row $3$ from rows $1$ and $2$ to put zeros in the (1, 3) and (2, 3) positions.

In [ ]:
#type your code here:

R[2,:] =R[2,:]/ R[2,2]
R[0,:] =R[0,:]-  R[0,2]*R[2,:]
R[1,:] =R[1,:] -  R[1,2]*R[2,:]
print(R)

[[nan nan nan nan]
 [nan nan nan nan]
 [nan nan nan nan]]


#### (d) Your matrix $R$ should now be transformed into $rref(A)$ (since $A$ is a random $3 \times 4$ matrix, $rref(A)$ is (almost) sure to have rank (3) `np.linalg.matrix_rank(R)`. Check your answer by python with the rref method . If the answer is not the same as the current value of your $R$, go back and redo your calculations.

- use the the built in rref method `sympy.rref()`
- print the output matrix in numpy array type



In [ ]:
#type your code here:

# Use sympy.rref() method
sympy_matrix = sym.Matrix(A).rref()[0]
numpy_rref = np.array(sympy_matrix).astype(float)

print("R = ", R)

print("numpy rref = ", numpy_rref)



R =  [[nan nan nan nan]
 [nan nan nan nan]
 [nan nan nan nan]]
numpy rred =  [[ 1. nan nan nan]
 [ 1. nan nan nan]
 [ 1. nan nan nan]]


# Question 5. Matrix Multiplication using Different views

There are different ways to do matrix multiplication $AB = C$ where $A$ and $B$ are arbitry matrices. If $A$ is an $m \times n$ matrix and $B$ is an $n \times p$ matrix, then $C$ is an $m \times p$ matrix of them are the following:

1. **Standard(row times column):** The standard way of describing a matrix product is to say that $c_(ij)$ equals the dot product of row $i$ of matrix $A$ and column $j$ of matrix $B$.

2. **Columns:** The product of matrix $A$ and column $j$ of matrix $B$ equals column $j$ of matrix  $C$. This tells us that the columns of $C$ are combinations of columns of $A$.


In this problem we will use python to perform the matrix multiplication using these different ways, and compute the execution time for each method time.

(Write your code as a function that perform the multiplication for arbitrary size of the matrices $A$ and $B$)

In [ ]:
def check_dimension(A, B):
  # We need to check the dimensions
  # type your code here
    return A.shape[1] == B.shape[0]

def mat_mul_standard(A, B):
    if not check_dimension(A, B):
        raise Exception('Dimensions aren\'t consistant')

    ################type your code here#####################
    m, n = A.shape
    n, p = B.shape

    C = np.zeros((m,p))

    for i in range(m):
        for j in range (p):
            C[i, j] = np.dot(A[i, :], B[:, j])
            
    return C


def mat_mul_columns(A, B):
    if not check_dimension(A, B):
        raise Exception('Dimensions aren\'t consistant')

    ################type your code here#####################
    m, n = A.shape
    n, p = B.shape

    C = np.zeros((m,p))

    for j in range(p):
        C[:, j] = A @ B[:, j]


    return C



In [ ]:
A = np.fix((10*(np.random.rand(300, 300))))
B = np.fix((10*(np.random.rand(300, 300))))

In [ ]:
%%time
#Multiply A @ B
A @ B

CPU times: total: 0 ns
Wall time: 1.13 ms


array([[5765., 6212., 5749., ..., 5811., 5917., 5671.],
       [5817., 6147., 5406., ..., 6064., 6091., 6059.],
       [5796., 6383., 5742., ..., 5839., 6144., 6062.],
       ...,
       [5546., 5806., 5552., ..., 5726., 5788., 5667.],
       [5677., 6109., 5453., ..., 5786., 5824., 5982.],
       [6042., 6446., 5692., ..., 6103., 6373., 5996.]], shape=(300, 300))

- Compare between the running time of the 2 methods:\
Multiply  the matrices with both methods and compare between efficiency of both according to their running time

In [ ]:
%%time
C_standard = mat_mul_standard(A, B)


CPU times: total: 141 ms
Wall time: 145 ms


In [ ]:
%%time
C_columns = mat_mul_columns(A, B)


CPU times: total: 0 ns
Wall time: 5.09 ms


The column method (mat_mul_columns) is significantly faster than the standard method (mat_mul_standard).